networks:
    default: development

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.0.0-rc.0

compiler:
    solc:
        optimizer:
            enabled: true
            runs: 200
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0-rc.0"

autofetch_sources: true

reports:
    exclude_contracts:
        - ERC20
        - Ownable
        - Context
        - Counters
